Ports Dynamic Gamemode Code from Beestation. (#8390)
* Adds support for dynamic mathing

* Adds Dynamic Main Files.

* Adds Dynamic loading to yogstation.dme

* Probably adds dynamic related changes.

* Fixes code I didn't add, won't fix my retardation.

* Adds "/datum/game_mode/proc/admin_panel()" because it's apparently important.

* Adds dynamic related code.

* Adds more dynamic related code.

* Fixes error: possible unreachable code here on line 313

* Fixes copy and paste error. 


code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm, line 390, column 2:
error: possible unreachable code here

* Adds a testing change to fix the lint

* Undos paranthesis

* LintFixTry#2

* Adds Shadowling

* adds a slash

* adds some logging

* Adds IMMERSION

Thank you Theos for the help!

* FIXES     IMMERSION

* Adds Mindshield Implants for Dynamic

* Adds the mindshield implant into dynamic

* Adds the mindshield stuff yadayadayda

* adds another slash

* removes said slash

* test addes imp_ before mindshield on line 427

* redo

* test

* Going to try and do this again #1

* syndie_kit/mindshield/

* gets rid of an error

* renames to imp_mindshield

* Maybe I'm just super retarded.

* v

* #include "code\game\objects\items\implants\implant_mindshieldtot.dm"

DOES THIS FIX IT DOES THIS FIX IT

* oops

* recompile

* Part of getting rid of weights, relies on dice rolls

* Adds dice roll, adds the ability for clock cult to roll

* Readjusts weight and costs, no more weight

* ahem fuck you travis or whatever the hell your name is - recompile

* Oh god oh fuck clock cult cost 0 for a while, oh god oh fuck meteors are now in, only coming in at threat 100 and higher. Shadowling requirement shifted,

* recompile

* Rev Fix

* Allows more midrounds to play

* Clockwork additions and whatnot

* Adds Vampire, and some changes to the requirements, and whatnot.

* Fixed Jobs to Roles

* Adds Vampire to Late Join

* Adds vampire cooldown to roundstart

* Adds Traitor_Ruleset to Vampire

* Adds Vamps to midround

* recompile

* Shadowling Modification

* Revs are now under the flag TRAITOR_RULESET, shadowling change, attempts to keep the round from ending if all the shadowlings die.

* Makes mindshield limited stock, now costs 1 tc, very small chance to show up in surplus crate, isn't illegal tech, player mininum is 30

* Adds cargo crate discounts

Thank you Jamie and Gamer for helping!

* Adds the party crate to discount

* Adds Zombies to the midround

* Recompile

* FUCK YOU RECOMPILE ALREADY

* recompile

* Jungle Fever can now roll.

* Only need one vampire candidate now.

* Fix

* Ah shit it seems you're utterly fucked.

* Update dynamic_rulesets_roundstart.dm

If set to TRUE, dynamic mode will be able to draft this ruleset again later on. (doesn't apply for roundstart rules(?))

* No Highpop req for shadowling

* Adds Darkspawn

* Adds some logging.

Co-authored-by: Theos <theubernyan@gmail.com>
Co-authored-by: fluffe9911 <dablank02@hotmail.com>