Update Yarn (3.3.1 -> 4.5.1) and Node (20.13.0 -> 22.11.0) (#5013)
* TGUI: bumps yarn version (#82385)

Bumps our bundled yarn version up to 4.1.1.

This seemed previously impossible due to an indecipherable error
message:
```
SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
```

I'm assuming this was a bug in (earlier) versions of yarn ~4.0.2.
Meaning, this is probably worth testing or test merging, as it seems to
be running fine currently.
Better build tools
N/A

* [tgui] Bumps node & yarn versions (#87700)

- Node 22 LTS and Yarn 4.5.1
- Removes windows 7 compatibility support
- Set to install for you on the next build
- CI also bumped to Node LTS
Oil change for TGUI. Up to date and fresh!

N/A

---------

Co-authored-by: Jeremiah <42397676+jlsnow301@users.noreply.github.com>